### ISSUE TITLE
"Verwaltungen" lost their WPML-permissions to translate

### ISSUE THREAD

**Issue by dkehne** [Integreat/cms#840]
Today i was phoned by two "Verwalter" from different cities who both lost their translations-permissions. All "Vertrauenswürdige Organisationen" still have their rights, only Verwalter are limited. I corrected it for those two persons, but one needs to find out what went wrong and how we can correct that in all instances.

**Comment by Ponitac** [comment]
Fixed in #844

**Comment by dkehne** [comment]
It's still a problem. There is a white page as "Verwalter". As "Vertrauenswürdige Organisation" it is working.

**Comment by dkehne** [comment]
with test it works, with kehnetest it does not. both have the same rights...

**Comment by svenseeberg** [comment]
It seems that this is not related to capabilities. Even granting all capabilities to a user does not fix the problem.
